name: warenkorb_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/grill.png
    - assets/hamburger.png
    - assets/meet.png
    - assets/noodle.png
    - assets/loading.png
    - assets/backround1.png
